"""empty message

Revision ID: 4e7537cb3831
Revises: ce691aef6851
Create Date: 2021-11-20 00:47:55.606617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7537cb3831'
down_revision = 'ce691aef6851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
