"""empty message

Revision ID: 74400897ea22
Revises: d1c424602eae
Create Date: 2021-11-18 17:57:44.040345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74400897ea22'
down_revision = 'd1c424602eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('price', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('student', sa.Column('email', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'email')
    op.drop_table('course')
    # ### end Alembic commands ###
