"""empty message

Revision ID: 76a4d8da0c29
Revises: b5f3c479d0a1
Create Date: 2021-12-14 17:07:50.801326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a4d8da0c29'
down_revision = 'b5f3c479d0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('password', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'password')
    # ### end Alembic commands ###
