"""empty message

Revision ID: becdcf2d5887
Revises: 1fbe781641cf
Create Date: 2021-11-18 20:47:30.754345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'becdcf2d5887'
down_revision = '1fbe781641cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('courses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='courses_course_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='courses_student_id_fkey'),
    sa.PrimaryKeyConstraint('student_id', 'course_id', name='courses_pkey')
    )
    op.drop_table('course_student')
    # ### end Alembic commands ###
